In [104]:
import nibabel as nib
import numpy as np
import os

In [105]:
data_path = 'Z:/home/majumdes/Datasets/Prospective_PPG/affine_testing/1569365'

with open('captk_affine.npy', 'rb') as f:
    A = np.load(f)

with open('orient.npy', 'rb') as f:
    ornt = np.load(f)

# open image
image_path = os.path.join(data_path, 'T1_VIBE_SPAIR_PRESAG_4.nii.gz')
image = nib.load(image_path)
image_header = image.header
print(image_header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 57
dim             : [  3  88 512 512   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.    2.9   0.469 0.469 0.015 0.    0.    0.   ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'TE=3.6;Time=100755.247;phase=1'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 1.2347709e-10
quatern_c       : -4.591598e-17
quatern_d       : -0.00087266456
qoffset_x       : -133.28143
qoffse

In [106]:
# open mask_itk
mask_itk_path = os.path.join(data_path, 'mask.nii.gz')
mask_itk = nib.load(mask_itk_path)
mask_itk_header = mask_itk.header

# open mask captk
mask_captk_path = os.path.join(data_path, 'mask_captk.nii.gz')
mask_captk = nib.load(mask_captk_path)
mask_captk_header = mask_captk.header
# print(mask_captk_header)

#open mask gandlf
mask_gandlf_path = os.path.join(data_path, '1569365_seg.nii.gz')
mask_gandlf = nib.load(mask_gandlf_path)
mask_gandlf_header = mask_gandlf.header

mask_itk_np = np.array(mask_itk.dataobj).astype(np.float64)
mask_gandlf_np = np.array(mask_gandlf.dataobj).astype(np.float64)

In [107]:
np.set_printoptions(precision=3, suppress=True)
print("Image affine: ")
print(image.affine)
print("CAPTK mask affine: ")
print(mask_captk.affine)
print("ITK mask affine: ")
print(mask_itk.affine)
print("gandlf mask affine: ")
print(mask_gandlf.affine)

Image affine: 
[[   2.9      0.001   -0.    -133.281]
 [  -0.005    0.469   -0.    -120.245]
 [  -0.       0.       0.469 -102.098]
 [   0.       0.       0.       1.   ]]
CAPTK mask affine: 
[[  -2.9      0.       0.     119.436]
 [   0.      -0.469    0.     118.846]
 [   0.       0.       0.469 -102.098]
 [   0.       0.       0.       1.   ]]
ITK mask affine: 
[[   2.9      0.001   -0.    -133.281]
 [  -0.005    0.469   -0.    -120.245]
 [  -0.       0.       0.469 -102.098]
 [   0.       0.       0.       1.   ]]
gandlf mask affine: 
[[   2.9      0.001   -0.    -133.281]
 [  -0.005    0.469   -0.    -120.245]
 [  -0.       0.       0.469 -102.098]
 [   0.       0.       0.       1.   ]]


In [108]:
print("Image pixdim: ")
print(image_header['pixdim'])
print("CAPTK mask affine: ")
print(mask_captk_header['pixdim'])
print("ITK mask affine: ")
print(mask_itk_header['pixdim'])
print("gandlf mask affine: ")
print(mask_gandlf_header['pixdim'])

Image pixdim: 
[1.    2.9   0.469 0.469 0.015 0.    0.    0.   ]
CAPTK mask affine: 
[1.    2.9   0.469 0.469 0.    0.    0.    0.   ]
ITK mask affine: 
[1.    2.9   0.469 0.469 0.    0.    0.    0.   ]
gandlf mask affine: 
[1.    2.9   0.469 0.469 0.    0.    0.    0.   ]


In [109]:
print("Image srow_x: ")
print(image_header['srow_x'])
print("CAPTK srow_x: ")
print(mask_captk_header['srow_x'])
print("ITK mask srow_x: ")
print(mask_itk_header['srow_x'])
print("gandlf mask srow_x: ")
print(mask_gandlf_header['srow_x'])

Image srow_x: 
[   2.9      0.001   -0.    -133.281]
CAPTK srow_x: 
[0. 0. 0. 0.]
ITK mask srow_x: 
[0. 0. 0. 0.]
gandlf mask srow_x: 
[   2.9      0.001   -0.    -133.281]


In [110]:
print("Image axes: ")
print(nib.aff2axcodes(image.affine))
print("CAPTK mask axes: ")
axs = nib.aff2axcodes(mask_captk.affine)
print(axs[0])
print("ITK mask srow_x: ")
print(print(nib.aff2axcodes(mask_itk.affine)))
print("gandlf axes: ")
print(print(nib.aff2axcodes(mask_gandlf.affine)))

Image axes: 
('R', 'A', 'S')
CAPTK mask axes: 
L
ITK mask srow_x: 
('R', 'A', 'S')
None
gandlf axes: 
('R', 'A', 'S')
None


In [111]:
# method 1
def check_orientation(ct_image, ct_arr):
    """
    Check the NIfTI orientation, and flip to  'RPS' if needed.
    :param ct_image: NIfTI file
    :param ct_arr: array file
    :return: array after flipping
    """
    x, y, z = nib.aff2axcodes(ct_image.affine)
    if x != 'L':
        ct_arr = np.flip(ct_arr, axis=0)
    if y != 'P':
        ct_arr = np.flip(ct_arr, axis=1)
    if z != 'S':
        ct_arr = np.flip(ct_arr, axis=2)
    return ct_arr

mask_itk_np_reorient = check_orientation(mask_itk, mask_itk_np)
new_nifti = nib.Nifti1Image(mask_itk_np_reorient.astype(np.float64), mask_captk.affine, mask_captk.header)
new_nifti.to_filename('Z:/home/majumdes/Datasets/Prospective_PPG/affine_testing/1569365/new_itksnap_flipped.nii.gz')

mask_gandlf_np_reorient = check_orientation(mask_gandlf, mask_gandlf_np)
new_nifti = nib.Nifti1Image(mask_gandlf_np_reorient.astype(np.float64), mask_captk.affine, mask_captk.header)
new_nifti.to_filename('Z:/home/majumdes/Datasets/Prospective_PPG/affine_testing/1569365/new_gandlf_flipped.nii.gz')

In [112]:
# method 2

print("CAPTK mask axes: ")
print(nib.orientations.axcodes2ornt(nib.aff2axcodes(mask_captk.affine), labels=None))
print("ITK mask axes: ")
print(nib.orientations.axcodes2ornt(nib.aff2axcodes(mask_itk.affine), labels=None))

ornt = np.array([[0, -1],
                [1, -1],
                [2, 1]])

# itk
itk_orient = mask_itk.as_reoriented(ornt)
flipped_affine_itk = A @ mask_itk.affine
itk_orient_copy = nib.Nifti1Image(itk_orient.dataobj, flipped_affine_itk, itk_orient.header) 
itk_orient_copy.to_filename('Z:/home/majumdes/Datasets/Prospective_PPG/affine_testing/1569365/new_itk_flipped2.nii.gz')

# gandlf
gandlf_orient = mask_gandlf.as_reoriented(ornt)
flipped_affine_gandlf = A @ mask_gandlf.affine
gandlf_orient_copy = nib.Nifti1Image(gandlf_orient.dataobj, flipped_affine_gandlf, gandlf_orient.header) 
gandlf_orient_copy.to_filename('Z:/home/majumdes/Datasets/Prospective_PPG/affine_testing/1569365/new_gandlf_flipped2.nii.gz')

CAPTK mask axes: 
[[ 0. -1.]
 [ 1. -1.]
 [ 2.  1.]]
ITK mask axes: 
[[0. 1.]
 [1. 1.]
 [2. 1.]]
